---
deployment:
  tasks:
    # Deploy the Next.js app from jobkaart-app folder to public_html
    - export DEPLOYPATH=/home/jobkaae5k2z4/public_html/
    - /bin/cp -R jobkaart-app/* $DEPLOYPATH
    - echo "Files deployed to $DEPLOYPATH"
