import { NextRequest, NextResponse } from 'next/server'
import { createServerClient, getTenantId } from '@/lib/db/supabase-server'

/**
 * POST /api/quotes/[id]/convert-to-job
 * Convert accepted quote to a job
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const tenantId = await getTenantId()

    if (!tenantId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const supabase = await createServerClient()

    // Get quote with customer details
    const { data: quote } = await supabase
      .from('quotes')
      .select(`
        *,
        customers!inner(name)
      `)
      .eq('id', id)
      .eq('tenant_id', tenantId)
      .single()

    if (!quote) {
      return NextResponse.json(
        { success: false, error: 'Quote not found' },
        { status: 404 }
      )
    }

    if (quote.status !== 'accepted') {
      return NextResponse.json(
        { success: false, error: 'Only accepted quotes can be converted to jobs' },
        { status: 400 }
      )
    }

    // Check if job already exists for this quote
    const { data: existingJob } = await supabase
      .from('jobs')
      .select('id')
      .eq('quote_id', id)
      .eq('tenant_id', tenantId)
      .single()

    if (existingJob) {
      return NextResponse.json(
        { success: false, error: 'Job already exists for this quote', job_id: existingJob.id },
        { status: 409 }
      )
    }

    // Create job (job_number will be auto-generated by database function)
    const { data: job, error: jobError } = await supabase
      .from('jobs')
      .insert({
        tenant_id: tenantId,
        customer_id: quote.customer_id,
        quote_id: id,
        job_number: '', // Will be generated by database
        title: `Job for ${quote.customers.name} - Quote ${quote.quote_number}`,
        description: quote.notes || '',
        status: 'scheduled',
      })
      .select(`
        *,
        customers!inner(id, name, phone, email, address)
      `)
      .single()

    if (jobError || !job) {
      console.error('Error creating job:', jobError)
      return NextResponse.json(
        { success: false, error: 'Failed to create job' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      data: {
        job,
        message: 'Quote converted to job successfully',
      },
    })
  } catch (error) {
    console.error('Unexpected error:', error)
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    )
  }
}
